# Export rom name
export VENDOR := cpa

# CPA2 Version info
CPA_VERSION_MAJOR := 1
CPA_VERSION_MINOR := 0
CPA_VERSION_MAINTENANCE := 0
CPA_CRYSTALPA := CrystalPA2

# PA Version info
PA_VERSION_MAJOR := 5
PA_VERSION_MINOR := 0
PA_VERSION_MAINTENANCE := 
PA_VERSION_TAG := ALPHA
